### ISSUE TITLE
Hand positions jump when Oculus loses tracking in 2018.2

### ISSUE THREAD

**Issue by julienkay** [ultraleap/UnityPlugin#1054]
Hey guys, I just updated to Unity 2018.2 and noticed a small issue. I know Unity 2018.2 just came out and isn't supported yet, so don't feel rushed to fix this. :)

However, I noticed during testing that my hands suddenly jumped to a lower position sometimes.
I realized this happens when Oculus loses tracking. I currently only have 1 sensor attached which means it's easy to occlude the sensor for a few frames when my hand is in front of the sensor.

My best guess would be that Unity may have changed the values `XRSupportUtil.GetXRNodeCenterEyeLocalPosition()` returns when tracking is lost, so XRServiceProvider uses zeroed out poses or something.

As far as I can see, this issue wasn't there in 2017.4.

EDIT: I meant InputTracking.GetLocalPosition() of course, which is wrapped by XRSupportUtil.

**Comment by julienkay** [comment]
After looking at this issue again, here's the workaround I'm using:

In XRServiceProvider i modified line 285-287:
https://github.com/leapmotion/UnityModules/blob/127374083128adbe6699c1ca96784a6d15d508f8/Assets/LeapMotion/Core/Scripts/LeapXRServiceProvider.cs#L285-L287

by replacing it with the following:
```csharp
// Get cached eyePos if InputTracking returns Vector3.zero due to lack of tracking
Vector3 eyePos = XRSupportUtil.GetXRNodeCenterEyeLocalPosition();
if (eyePos == Vector3.zero) {
        eyePos = _cachedCamera.transform.localPosition;
}

// Get most recent tracked pose.
Pose trackedPose = new Pose(eyePos, XRSupportUtil.GetXRNodeCenterEyeLocalRotation());
```

This solves the issue at hand, because InputTracking does indeed return a zero vector for GetLocalPosition(XRNode.CenterEye). This seems strange as Unity doesn't set the camera to the world origin when tracking is lost, so it might be a bug with Unity.
This is also only the case for Oculus as far as I know. The Vive seems to report the last position of the headset even if tracking is lost.

**Comment by julienkay** [comment]
This is still an issue for me (currently on Unity 2018.3.10f1), but the aforementioned fix has some flaws.

For Oculus the issue was completely reproducible. If the headset is untracked, InputTracking returns a zero vector while _cachedCamera.transform.localPosition is non-zero.

In rare cases, that are hard to reproduce (actually only happens with SteamVR/HTC Vive), sometimes the opposite happens: _cachedCamera.transform.localPosition returns Vector3.zero, while InputTracking already returns some tracked value. The bad thing is, that this seems to happen in the first frame. In those cases the _trackingBaseDeltaPose that is calculated in the first frame leads to the hands having a wrong offset which can't be recovered from without restarting the application.

I use the following code as workaround right now:

```
Pose trackedPose;      
if (XRSupportUtil.GetXRNodeCenterEyeLocalPosition() == Vector3.zero || _cachedCamera.transform.localPosition == Vector3.zero) {
  trackedPose = _cachedCamera.transform.ToLocalPose();
} else {
  trackedPose = new Pose(XRSupportUtil.GetXRNodeCenterEyeLocalPosition(), XRSupportUtil.GetXRNodeCenterEyeLocalRotation());
}
```

**Comment by Ultraleap-Dan** [comment]
Please can you test in Unity 2019 and let us know if this is still an issue?

**Comment by julienkay** [comment]
Yes, the issue with Oculus Rift CV1 is completely reproducible on 2019.4.4f1 (and also through the 2020 cycle as far as i can see).

The gist is:
**Issue**: On Rift CV1 you can't rely on getting valid positional data from Unity when the HMD is untracked. This seems to be still the case even though in 2019 the XRSupportUtil class switched from "InputTracking.GetLocalPosition" to the newer "XRNodeState.TryGetPosition()" API.
**Workaround**: In case the position/rotation reported by the Unity API is likely wrong, I use the position/rotation values of the camera transform instead.

The other issue that sometimes happened on Vive is harder to reproduce as I mentioned, but is more critical since the hands _trackingBaseDeltaPose is assinged an incorrect value, which can't be recovered from.

**Comment by Ultraleap-Dan** [comment]
Thank you for getting back to us, this is being raised internally as a bug for further investigation.

**Comment by Ultraleap-Dan** [comment]
Please be aware that Unity 2019 LTS is our earliest supported Unity version so this issue will be investigated but we will not be looking at any issues in previous versions.

**Comment by MaxPalmer-UH** [comment]
Confirmed the behaviour is as described and that a variant of the fix works fine.

**Comment by MaxPalmer-UH** [comment]
Was fixed in a release of the Unity Plugin.
