### ISSUE TITLE
ClearContactTracking() doesn't clear a pooled Hashset before calling Recycle()

### ISSUE THREAD

**Issue by julienkay** [ultraleap/UnityPlugin#1061]
https://github.com/leapmotion/UnityModules/blob/ff63f37fd07b4361cb91752b7e2e0bdbae4dee52/Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionController.cs#L1498-L1500

The pool class mentions to clean up objects yourself when using types that dont implement IPoolable.
Not calling tempObjs.Clear() here seems to be a mistake?
I'm investigating, because we've been having issues with hands getting stuck in soft contact, but I'm not sure this has anything to do with it.

**Comment by nickjbenson** [comment]
Yes, if tempObjs is filled with anything, it should be cleared before the recycle.

Generally I Clear before AND after using an object from the Pool so that an error like this minimizes the resulting bugs.

**Comment by Ultraleap-Dan** [comment]
This is under review.

**Comment by MaxPalmer-UH** [comment]
@julienkay The suggested change has been included in the code. Thanks for taking the time to point out the need for this change.
