### ISSUE TITLE
enableContactBoneCollision() called unnecessarily often

### ISSUE THREAD

**Issue by julienkay** [ultraleap/UnityPlugin#1062]
https://github.com/leapmotion/UnityModules/blob/ff63f37fd07b4361cb91752b7e2e0bdbae4dee52/Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionController.cs#L1343-L1345
There should no need to call this inside a loop, since enableContactBoneCollision() itself iterates over the contact bones, right? Probably a minor impact on performance, but still.

**Comment by Ultraleap-Dan** [comment]
This is under review.

**Comment by MaxPalmer-UH** [comment]
This change has been incorporated into the plugin. Many thanks.
