### ISSUE TITLE
VectorHand - OverflowException: Value was either too large or too small for an Int16.

### ISSUE THREAD

**Issue by darrencperry** [ultraleap/UnityPlugin#1080]
**Issue:**

Use FillBytes to encode your hand(s) and get the error:
`OverflowException: Value was either too large or too small for an Int16.`

from line:
`LeapMotion/Core/Scripts/Encoding/VectorHand.cs:239)`

**Reproduce:**

- Start a new scene, remove the main camera, drag Leap Rig prefab into scene.
- Add the following script to the Leap Rig Game Object

```
using Leap;
using Leap.Unity;
using Leap.Unity.Encoding;
using UnityEngine;

public class LeapTestVector : MonoBehaviour
{
    LeapXRServiceProvider leap;
    VectorHand vectorHand = new VectorHand();

    void Start()
    {
        leap = GetComponentInChildren<LeapXRServiceProvider>();
        leap.OnUpdateFrame += OnUpdateFrame;
    }

    private void OnUpdateFrame(Frame obj)
    {
        byte[] leftHandBytes = null;
        byte[] rightHandBytes = null;
        foreach (Hand hand in obj.Hands)
        {
            vectorHand.Encode(hand);
            if (hand.IsLeft)
            {
                leftHandBytes = new byte[86];
                vectorHand.FillBytes(leftHandBytes);
            }
            else
            {
                rightHandBytes = new byte[86];
                vectorHand.FillBytes(rightHandBytes);
            }
        }

    }
}
```
- Move the Leap Rig's X or Z Position to 8 or -8.
- See errors.

Am I using VectorHand wrong? Above is just a snippet of the code I'm using, I know I can tidy it up, I'm sending the byte array over the network to show hands on other clients...

**Comment by darrencperry** [comment]
If we encode the VectorHand with Int32 instead of Int16 for Palm Position then we need 6 more bytes, which I'm fine with.

VectorHand.cs:

193:
        `public int numBytesRequired { get { return 92; } }`
216:
         `BitConverterNonAlloc.ToInt32(bytes, ref offset))`
261:
         `BitConverterNonAlloc.GetBytes(Convert.ToInt32(palmPos[i] * 4096f),`

**Comment by MaxPalmer-UH** [comment]
Added this as a potential bug to our backlog. Are you saying that the Int16 isn't sufficient to encode the palm position and therefore you need to increase its size to an int32? If so, the other changes you make are needed to get it to stream correctly now the size is larger.

**Comment by MaxPalmer-UH** [comment]
Tracked as a breaking feature reques/bug. UNITY-762. Closing here.

**Comment by noxowl** [comment]
Still not fixed? It occurs when I try to encode a replicated hand via PostProcessor.

**Comment by MattGrayUL** [comment]
> Still not fixed? It occurs when I try to encode a replicated hand via PostProcessor.

Hmm, it seems we have marked this as a ticket we _won't do_. I will re-open it, though can't promise when it will get looked at 😬
