### ISSUE TITLE
[InteractionModule] Initializing contact bones of XR controller error ( trigger colliders )

### ISSUE THREAD

**Issue by kosipovic** [ultraleap/UnityPlugin#1085]
Script: InteractionXRController.cs
Line: 612 / 619

When you create contact bones , you skip trigger colliders, but in the loop you reference _contactBoneBuffer[i] , whereas numBones = _colliderBuffer.Count, which gives error OutOfRange if we have trigger collider inside the controller. 

Am I seeing it correctly? it needs to be : 
 int numBones = _contactBoneBuffer.Count; instead of  int numBones = _colliderBuffer.Count;

**Comment by nickjbenson** [comment]
If you wind up implementing this and seeing it address a bug, please make a PR and I'd be happy to review it! :)

**Comment by MaxPalmer-UH** [comment]
Now fixed.
