### ISSUE TITLE
InteractionButtons not working on moving platform

### ISSUE THREAD

**Issue by slimshader** [ultraleap/UnityPlugin#1152]
Hi,

When "installed" on a moving platform InteractionButtons get up or down with platform's movement making them unusable. The video showing the issue with first moving forward then backwards:

https://youtu.be/V9wt1PZK_ZY

I've looked at the docs and example 7 in the demos, problem is, it is not possible to to move the platform inside OnPrePhysicalUpdate callback because platform is being moved by 3rd party asset (simulating vehicle physics).

I've tried to at least do Physics.SyncTransforms(); in the callback while making sure that platform's FixedUpdate() is before InteractionManagers, which is also parented to a moving platform, still no dice.

Please advice.

Btw. using Core 4.4.0 with interaction engine 1.2.0

**Comment by Ultraleap-Dan** [comment]
We have added this to our engineering request list to investigate further.

**Comment by Ultraleap-Dan** [comment]
We would recommend that you have a look at the Frame and Physics Extrapolation settings on the Leap Providers which should help with this.

Another place that we have seen moving hands working is in the Interaction Engine. There is an example scene called Moving Reference Frames that allows you to interact with objects whilst still moving.

**Comment by slimshader** [comment]
> We would recommend that you have a look at the Frame and Physics Extrapolation settings on the Leap Providers which should help with this.

It didn't

> 
> Another place that we have seen moving hands working is in the Interaction Engine. There is an example scene called Moving Reference Frames that allows you to interact with objects whilst still moving.

"example 7" I mentioned I checked IS the "Moving Reference Frames", I followed it and the corresponding docs, I thought it was clear from my report. The example platform tho is NOT moved by Rigidbody which is the source of the problem. The way to reproduce the issue is easy, just place some buttons on the platform moved by Rigidbody forces and everything stops working when moving faster than 10 km/h.

**Comment by Ultraleap-Dan** [comment]
This is fixed in version 5.3 of our plugin, please can you update and retest?
