### ISSUE TITLE
'SelectionMode.OnlyUserModifiable' is obsolete

### ISSUE THREAD

**Issue by albrrt** [ultraleap/UnityPlugin#1167]
When importing the Core module in Unity 2019.4.31f1 (LTS) I get 3 errors:

`error CS0619: 'SelectionMode.OnlyUserModifiable' is obsolete: ''OnlyUserModifiable' is obsolete. Use 'Editable' instead. (UnityUpgradeable) -> Editable'`

![Capture](https://user-images.githubusercontent.com/28485330/138275492-b5ba89bb-290e-4db9-b98b-f8930344ec9b.JPG)
``
I downloaded the package today from https://developer.leapmotion.com/unity 

I know it's an easy fix but if someone can fix the downloadable package on the website, it would be really helpful.

Thanks!

**Comment by zalo** [comment]
[The fix (and others) are in `develop`](https://github.com/leapmotion/UnityModules/blob/develop/Assets/Plugins/LeapMotion/Core/Editor/Hotkeys.cs#L24), but have not made it to the website yet.

**Comment by ElliotPadfieldUL** [comment]
As @zalo mentioned above, this fix has made it into develop and is part of the Unity Plugin 5.0.0 Release.
