### ISSUE TITLE
Issue on getting Device Serial Number

### ISSUE THREAD

**Issue by hongkai0818** [ultraleap/UnityPlugin#1171]
In previous unitymodules, we can get leapmotion device serial number using 
Device leapDevice = controller.Devices[0];
Debug.Log(leapDevice.SerialNumber);

However, after updating to 4.9.1, it will only return device_1.

Is there any issue or update on this?

**Comment by Ultraleap-Dan** [comment]
Hi @hongkai0818, I am adding a note here for anyone else who reads this. Thank you for raising a support ticket as well for this. This issue is currently assigned to our engineering team for investigation and I will post any updates here and to you directly as they become available.

**Comment by MaxPalmer-UH** [comment]
Fix for this will be in the next release of the service (V5.4).

**Comment by hongkai0818** [comment]
Hi, thanks for your reply. Any estimated timeline for the release of tracking service (v.5.4)?
