### ISSUE TITLE
[Documentation] Missing rigged hands image

### ISSUE THREAD

**Issue by Michal-Jankowski** [ultraleap/UnityPlugin#1172]
Hi,
 when you enter the docs site under Core/LeapMotionXRrigs the second image described as "Rigged Hands" is not loaded.
 I suspect this line _![Rigged Hands](@ref images/RiggedHands.png)_ under docs/content/100-Core.md, which references to _images_ directory that surprisingly does not have it.
![image](https://user-images.githubusercontent.com/32636855/144217994-a2da7db6-9c16-4553-a8be-8abb22503412.png)

**Comment by ElliotPadfieldUL** [comment]
We have a new docs site with updated content, please let us know if you find any issues. [https://docs.ultraleap.com/unity-api/unity-user-manual/getting-started.html](url)

Closing this issue for now.
