### ISSUE TITLE
Handtracking of Stereo IR 170 not working with MRTK 2.7.2 + Oculus Quest 2

### ISSUE THREAD

**Issue by smfrue** [ultraleap/UnityPlugin#1174]
Hello,

I don't get IR 170 to work with MRTK. I'm following the instructions [here](https://developer.leapmotion.com/mrtk-unity) but without success. It always keeps using the oculus quest handtracking. 

I get the ultraleap examples to work. In past experiments MRTK worked seamlessly with leap motion (with HoloLens2) but now with Quest 2 and IR 170 it doesn't work. Anything I can do or is it just not tested yet with this setup?

Thanks for your help!

System Versions:
Oculus Quest 2 (Integration v35)
Unity 2020.3.24f1
MRTK 2.7.2
Ultraleap Handtracking Software 5.3.1
Ultraleap Unity Modules 5.0.0

**Comment by MaxPalmer-UH** [comment]
We are currently working on a merge request for the MRTK repo to support Unity Modules V5.0.0, which we hope to submit soon.

**Comment by smfrue** [comment]
Okay thanks a lot! Can you approx. estimate how long it could take? Like 2 weeks, 1 month or more? Our quality of research will be a bit dependant of that. Would be awesome if it's possible to work with your modules in MRTK next month <3

**Comment by smfrue** [comment]
> We are currently working on a merge request for the MRTK repo to support Unity Modules V5.0.0, which we hope to submit soon.

Any news regarding that?

**Comment by MaxPalmer-UH** [comment]
Hi Simon, just got back from holiday. Should be back on it in the next couple of days, so hopefully very soon (a few days) - at least to get to a PR/MR.

**Comment by smfrue** [comment]
Thanks appreciate it! My colleague just told me that it worked perfectly on Valve Index with the basic Leap Motion settings. I assume the problem is Quest's handtracking integration in MRTK then, which needs to be replaced in a way. Will it be possible with your fix to switch between hands and controllers like before?

**Comment by MaxPalmer-UH** [comment]
An update on this, we've discovered a compatibility issue with V5.0.0 -> V5.1 and MRTK, so we're working on an update that will enable the modules to be used with MRTK. It's being worked on now.

**Comment by smfrue** [comment]
Any news regarding that? @MaxPalmer-UH

**Comment by MaxPalmer-UH** [comment]
@smfrue after a bit of a delay 5.3 is now out.

**Comment by MaxPalmer-UH** [comment]
Well, it should be in a few minutes. UPM is up but you'll need the unitypackages from here for MRTK.

**Comment by MaxPalmer-UH** [comment]
Now out

**Comment by smfrue** [comment]
I've uninstalled the previous version of ultraleap unity modules, installed 5.4 over UPM + updated Gemini to 5.4. Then I tried to integrate Leap Motion Unity Modules into MRTK but I'm getting this error message. Anything I'm doing wrong? Thanks a lot for your help. Do I have to update sth of MRTK? I've got MRTK 2.7.3.

`DirectoryNotFoundException: Could not find a part of the path "D:\Unity\Unity Frameworks\MRTK\OmnitouchExp\Assets\Library\PackageCache\com.ultraleap.tracking@5.4.0\Core\LeapMotion\Core\Version.txt".
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.StreamReader..ctor (System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
Microsoft.MixedReality.Toolkit.LeapMotion.LeapMotionConfigurationChecker.LeapCoreAssetsVersionSupport () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@127cdd699138-1640103740604/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs:167)
Microsoft.MixedReality.Toolkit.LeapMotion.LeapMotionConfigurationChecker.ConfigureLeapMotion (System.Boolean isLeapInProject) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@127cdd699138-1640103740604/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs:131)
Microsoft.MixedReality.Toolkit.LeapMotion.LeapMotionConfigurationChecker.IntegrateLeapMotionWithMRTK () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@127cdd699138-1640103740604/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs:476)
`

**Comment by MaxPalmer-UH** [comment]
A few things to note. Support for our Unity Plugin in MRTK is based on a whitelist of supported versions. The merge request to support V5.3.0 of the Unity Plugin in MRTK has been approved and merged. However, it's not currently in a release - as no release has been made since it was merged. To get this working, you would need to fetch code from the **main** MRTK branch and integrate **V5.3.0** of the plugin. **It will not work with other version of V5.**
