### ISSUE TITLE
Bug when saving prefab

### ISSUE THREAD

**Issue by MarchenkoSI** [ultraleap/UnityPlugin#1177]
Greetings!

The bug appears if you save the prefab on which the Hand Binder script is located. Unity starts trying to save it and is constantly updating. Also, this prefab is not always possible to remove from the project folder the first time.

Unity Plugin 5.0.0 / 5.1.0
Unity 2019.4.0f1 / 2020.3.23f1

Reproduce:

1) Create any object in any scene.
2) Add a Hand Binder script to this object
3) Save object as prefab
4) Select a prefab in the project folder

https://youtu.be/7Y4f1WxM1OM

**Comment by ElliotPadfieldUL** [comment]
Hello, thanks for reporting a bug. 

For now, if you jump into the HandBinderEditor.cs and comment out line 106 //EditorUtility.SetDirty(target) this will fix the issue. 

We will look into fixing this issue in the next release :)

**Comment by MaxPalmer-UH** [comment]
Fix is now in this commit: https://github.com/ultraleap/UnityPlugin/commit/a2e1db962f1114d5384690cc7d7266768d4b1861#diff-a235c2de4c3a2707585f7ea75ac49af94891baa715a0742b3f3ebcd47b4d12fb
