### ISSUE TITLE
Bug developed using LeapMotion + Oculus Quest2 between Unity Editor and Build App for Windows

### ISSUE THREAD

**Issue by hyoung0416** [ultraleap/UnityPlugin#1178]
Greeting!
I just set OVRCameraRig and LeapMotion in an empty scene, but the tracking position is different.
I've continued to search, but I can't find anything related to it, so I'm posting it here.

Editor Image

![Editor1](https://user-images.githubusercontent.com/83275330/149731429-c017cbde-7df5-4ecf-8d31-4abf7b7fc27d.gif)
Build App Image

![build1](https://user-images.githubusercontent.com/83275330/149731442-e4c5e153-2f73-41b3-a7e5-4f2252334fbd.gif)

To indicate the position of the leap motion controller, I placed three red, blue, and yellow in order.

**Comment by Ultraleap-Dan** [comment]
Hi, please can you let me know which version of Unity and our Unity Plugin you are using?
