### ISSUE TITLE
ExtendedFingerDetector doesn’t work with OpenXR

### ISSUE THREAD

**Issue by Ronan-V** [ultraleap/UnityPlugin#1206]
### _Open XR Leap Provider_ and _ExtendedFingerDetector.cs_ with the Unity plugin v5.11.0.
The issue is that _ExtendedFingerDetector_ doesn't seem to work with the OpenXR provider while it does with the _Leap XR Service Provider_. All fingers are detected as extended whatever their position.

**To reproduce**
1. Open the example scene _Capsule Hands (OpenXR)_.
2. Add _Extended Finger Detector_ script to any hand _Capsule Hand Left_ and/or _Capsule Hand Right_.
3. Check detector's activation state with Gizmos or _On Activate()_ and _On Deactivate()_ events.

**Comment by MaxPalmer-UH** [comment]
Unfortunately the OpenXRProvider does not support a few features that are provided through the LeapC interface. 

The OpenXR Leap Provider does not currently support the following hand properties (and will return fixed values): 
•	Hand and Finger: FrameId
•	Hand: Confidence
•	Hand: GrabAngle
•	Hand and Finger: Id & HandId will always return 0 and 1 for the left and right hand respectively
•	Hand and Finger: TimeVisible
•	Finger: IsExtended

**Comment by MaxPalmer-UH** [comment]
This is now being worked on

**Comment by MaxPalmer-UH** [comment]
@Ronan-V this (and a few other OpenXR missing features) should be going through QA next week and will hopefully make it into 5.13.0.
