### ISSUE TITLE
Plugin shouldn't force TrackedPoseDriver when using XR Plugin Management

### ISSUE THREAD

**Issue by nwessing** [ultraleap/UnityPlugin#1393]
Our application uses Unity's XR plugin management, but not `TrackedPoseDriver` (we have our own implementation). We have trouble using this plugin since it adds `TrackedPoseDriver` to our camera, the problematic code is here:

https://github.com/ultraleap/UnityPlugin/blob/d7d141896574c4dcf0804a7d37ed125e92b475aa/Packages/Tracking/Core/Runtime/Scripts/LeapXRServiceProvider.cs#L316-L321

**Comment by MattGrayUL** [comment]
Thanks @nwessing, i'll link this issue to the ticket and see if we can make this feature optional soon :)

**Comment by nwessing** [comment]
That is great, thank you!
