### ISSUE TITLE
OpenXRLeapProvider not loaded

### ISSUE THREAD

**Issue by tomh4** [ultraleap/UnityPlugin#1443]
I am trying to use the OpenXR Leap Provider, but the script seems to have an issue, as it is not being loaded
![image](https://github.com/ultraleap/UnityPlugin/assets/19487549/78e6d1cc-8b2d-4d4f-b915-340fea4a747b)

There are no errors, and I am using Unity 2021.3.22f and the latest package (6.8.0) of this plugin

**Comment by MattGrayUL** [comment]
Hi @tomh4

The OpenXR content of the Plugin will only load if you also have the Unity OpenXR package imported. Have you imported it via the Unity Package Manager?

**Comment by MattGrayUL** [comment]
I would expect so, as that should also need OpenXR

If you open the Package Manager window, do you have this?
![image](https://github.com/ultraleap/UnityPlugin/assets/60962475/4281b6b8-44e8-4d89-9ac4-fd5310bc8ee6)

**Comment by tomh4** [comment]
No, as Oculus is using their own OpenXR implementation 

"Note: The OpenXR backend mentioned in this topic is different than [Unity OpenXR plugin](https://www.oculus.com/lynx/?u=https%3A%2F%2Fdocs.unity3d.com%2FPackages%2Fcom.unity.xr.openxr%401.5%2Fmanual%2Findex.html&e=AT06JNOk_tRTdlHK1jAFt93ZLTcyu-einxMH2YS2irFtJ6O2MgNhWAiLm3LjyLeco_vgQ_sjOFH8WL1puKzHX-qalNpRb1nbixpmiP2mNPqCpLwKurE6DnsvGyGdkaAzndMZr4aJ_HkrUetz6_JOxw)."

I started writing a custom OculusLeapProvider, but if this can be avoided by just "enabling" Oculus' OpenXR Runtime, that would be great

**Comment by MattGrayUL** [comment]
Ah yeah, our OpenXR implementation requires Unitys OpenXR Plugin, not Oculus'

We have an older Oculus-to-Leap provider available [here](https://github.com/ultraleap/UnityPlugin/blob/com.ultraleap.tracking/6.4.0/Packages/Tracking%20Preview/OVR%20Provider~/Scripts/OVRLeapProvider.cs) if you wanted to try it out, or use it as a base, but it was removed in January in favor of Unitys OpenXR implementation - it was from the Ultraleap Tracking Preview Package in version 6.5.0

**Comment by tomh4** [comment]
@MattGrayUL thanks that will help,
would you be interested in the result? Should I share it? Or do you prefer keeping the OpenXR way ?

**Comment by tomh4** [comment]
@MattGrayUL so far so good, this is were I get with the Oculus Provider:

https://github.com/ultraleap/UnityPlugin/assets/19487549/66b450ac-6387-4ef2-bc73-0fc982fdb25b

As you can see, the thumb is offset as well as the palm itself.
Do you have any idea where I might look to improve this?

**Comment by tomh4** [comment]
@MattGrayUL  any ideas? I tried to play around with the offsets, but it is not really helping :(

**Comment by MattGrayUL** [comment]
I think this might relate to the way that Meta produce their hand data as we have seen mismatches between the data sets positions before

@rorygames may be better placed as he knows Physics Hands better than me though

**Comment by rorygames** [comment]
From what I've been told, the Oculus hands don't currently conform to the OpenXR spec entirely which makes them report differently to what's expected. I'm not able to do a huge amount about this within the Physics Hands realm as I can't tell exactly what's currently being used (whether it's OpenXR Ultraleap hands vs OpenXR Oculus hands). When the hands conform better from all ends then things should be better (but I obviously don't know when that will happen on the Oculus side).

**Comment by tomh4** [comment]
Thanks for the quick reply @rorygames  
So from what I can see, we have a metacarpal thumb and pinky, and the wrist seems to have a new offset.
The wrist I can balance out, and by setting the thumb metacarpal to the thumbs proximal, i get a "somewhat" acceptable result but I would definitely want to improve on this. 
I am currently using the vector hand to leap hand "Decode", and I would rather not change a lot in there as I guess this is used on other places as well, so I would like to modify my OculusProvider in such a way as to convert the hand correctly.

Do you have any documentation or similar which shows me what the expected input is?

**Comment by rorygames** [comment]
I'm kind of amazed that that's working as it is currently 😅 (pretty sure VectorHand nukes a few variables that physics hands makes use of).

So by default we're expecting the hands to come in as basic OpenXR hands, which then get slightly modified by the openxr provider (to make them conform back to Leap version hands, idea being that if the data is conformant then we're all good).
The offsets are initial hand positions are set from a default hand pose we create off of our "TestHandFactory" script. You can see the flow of the offsets initial values by following the [generation functions](https://github.com/ultraleap/UnityPlugin/tree/develop/Packages/Tracking%20Preview/PhysicsHands/Runtime/PhysicsProvider.cs#L279). Following it through you'll see a function called TestHandFactory.MakeTestHand which gives the default poses of the hand that you see in the editor outside of play mode.
You can also see that we offset the thumb angle within the Setup stage of the physics hand which is located in the [PhysicsHandUtils](ttps://github.com/ultraleap/UnityPlugin/tree/develop/Packages/Tracking%20Preview/PhysicsHands/Runtime/Utils/PhysicsHandsUtils.cs#L229). This also happens within the ResetPhysicsHandSizes function within the same script (which is called when the hand regains tracking).

I don't personally use a Quest (nor have spent much time with the hand tracking coming from it) but those areas should help you find _what_ you might need to modify 🤞

**Comment by rorygames** [comment]
VectorHand is designed for use within networking, so currently just reports the absolute minimal version of a hand that can be used for visual reconstruction but shouldn't be fully relied on for accuracy (it also reduces some variable precision which can result in a bit of jumping/rounding).

**Comment by tomh4** [comment]
Okay thanks, so I will go the OpenXRLeapProvider way, I will report back if I make any progress :)

**Comment by tomh4** [comment]
so im pretty close to what I want now @rorygames , but the thumb is still acting weird.

https://github.com/ultraleap/UnityPlugin/assets/19487549/43653fe1-088b-4e94-8691-ec9b8fb26bc6

The rotation coming from oculus is splitted partially into the metacarpal of the thumb, and the proximal. I am not sure if the physics hand is correctly interpreting non-identity rotations of the 0-th bone of the thumb?
