### ISSUE TITLE
Error on HandPoseValidator.cs script

### ISSUE THREAD

**Issue by hongkai0818** [ultraleap/UnityPlugin#1453]
Hi, in the unity editor, after I update to version 6.8.1 from 6.6.0, there are errors on the handposevalidator script on line 93 and 94. (refer to attached screenshot) 
<img width="1079" alt="Screenshot 2023-06-01 at 9 29 50 AM" src="https://github.com/ultraleap/UnityPlugin/assets/31461081/8f7b160f-6187-4da8-afeb-d27d96453eb8">

Utils.Fill(leftCapsuleHandColours, Color.grey);
Utils.Fill(rightCapsuleHandColours, Color.grey);

For my case, I solved the issue by adding:
Leap.Unity.Utils.Fill(leftCapsuleHandColours, Color.grey);
Leap.Unity.Utils.Fill(rightCapsuleHandColours, Color.grey);

**Comment by MattGrayUL** [comment]
Pull request for this is here, we will review it and hopefully get it into the next release :) https://github.com/ultraleap/UnityPlugin/pull/1456

**Comment by MattGrayUL** [comment]
This was auto-closed due to the merge - it will be released in the next release of the Plugin :)
