### ISSUE TITLE
HandPoseDetector IndexOutOfRangeException

### ISSUE THREAD

**Issue by cubesky** [ultraleap/UnityPlugin#1512]
When I using HandPoseDectector, on Line 353, it will call 

```
Vector2 jointRotationThresholds = GetBoneRotationThreshold(pose, fingerNum, boneNum - 1);
```

But when the boneNum is 0, it will call `GetBoneRotationThreshold(pose, fingerNum, -1)` and then `HandPoseScriptableObject` will access `return fingerJointRotationThresholds[fingerNum].jointThresholds[boneNum];` on Line 119. boneNum will `-1` and trigger IndexOutOfRangeException.

**Comment by MattGrayUL** [comment]
Hi @cubesky sorry for a late reply!

I am not sure it's possible to get to that line of code if the boneNum is 0 

boneNum relates to the joints index where 0 is the metacarpal. The check just above in this loop will continue to the next index if the BoneType is Metacarpal:

>                     //Ignore the metacarpal as it will never really change.
>                     if (serializedHandBone.Type == Bone.BoneType.TYPE_METACARPAL)
>                     {
>                         lastBoneRotation = activeHandBone.Rotation;
>                         lastSerializedBoneRotation = serializedHandBone.Rotation;
>                         continue;
>                     }


Are you actually getting this IndexOutOfRangeException? if so, I am happy to add an explicit check for boneNum == 0

**Comment by cubesky** [comment]
Yes, I got this Exception. 
![image](https://github.com/ultraleap/UnityPlugin/assets/8038511/6ef1b7c6-0428-4b11-bc52-5f922d768a21)

I'm using Pose Detector, but I can not find any example for Pose Detector on this version. So I use the following code on Pose Detector.

```csharp
using Leap.Unity;
using UnityEngine;

[CreateAssetMenu(fileName = "GrabPose", menuName = "ScriptableObjects/GrabPoseScriptableObject", order = 1)]
public class GrabPose : HandPoseScriptableObject
{
    public GrabPose() { 
        for (int i = 0; i < 5; i++)
        {
            this.fingerJointRotationThresholds[i].jointThresholds = new [] { 
                new Vector2(0,0),new Vector2(0,0),new Vector2(0,0),new Vector2(0,0),new Vector2(0,0)
            };
        }
        SetAllBoneThresholds(0.8f, true);
        Debug.Log(this.fingerJointRotationThresholds.Length);
    }
}
```

**Comment by MattGrayUL** [comment]
Ah, the Poses are not intended to be made via code - but it's good that you've drawn our attention to it!

If you are hoping to detect grabs, I recommend using the [code paths for this](https://docs.ultraleap.com/xr-and-tabletop/xr/unity/plugin/features/pinch-and-grab-detection.html), as "grab" can often mean different things for different people, so isn't best represented as a pose (a complete shape)

If you do, however want to use Poses:

We actually have a collection of Poses that ship with the plugin, [discussed in this docs page](https://docs.ultraleap.com/xr-and-tabletop/xr/unity/plugin/features/hand-pose-detection.html) 

![image](https://github.com/ultraleap/UnityPlugin/assets/60962475/af845b57-ca74-4432-9939-5d85905b2aea)

You can also produce your own Poses by using the Pose Recorder Example Scene discussed [here](https://docs.ultraleap.com/xr-and-tabletop/xr/unity/plugin/features/pose-recording.html)

**Comment by cubesky** [comment]
Oh, Hand Pose doesn't show up in Unity, and the document not mention it.

![image](https://github.com/ultraleap/UnityPlugin/assets/8038511/54bd6f14-33dc-4e75-bae8-e4b660f9d1ee)

I find it in the sdk forwarding your image! Thanks

**Comment by MattGrayUL** [comment]
Ah, I see! That is because it's in the Packages folder, not Assets or Scene, which Unity hides by default 🤦 (see the hidden files in this screenshot!)

![image](https://github.com/ultraleap/UnityPlugin/assets/60962475/600383cb-ce71-426d-9ff0-91b44a9ca44c)

**Comment by cubesky** [comment]
Oh! Thanks! Now I can see them in select dialog. May be a document update for this?

**Comment by MattGrayUL** [comment]
I will raise a ticket for it :)

Thanks for raising this issue, I will now close it
