### ISSUE TITLE
Physical Hands Settings , vs . issue

### ISSUE THREAD

**Issue by tomh4** [ultraleap/UnityPlugin#1593]
With the latest version of Physical Hands, the Apply of the suggested physics settings no longer works , because it seems there is an issue with encoding of floating values.

![image](https://github.com/ultraleap/UnityPlugin/assets/19487549/15638a2a-a7f6-457b-9fd5-d6a7c8c675bd)

If I hit apply it messes up the settings because Unity is using e.g. 0,001 but the tool tries to write 0.001 to it.

Might be a localisation issue as well, I am based in Europe if that helps

**Comment by MattGrayUL** [comment]
Wow, thanks for raising this! Definitely looks like a localization issue - i'll feed it back into the team

**Comment by MattGrayUL** [comment]
This has been actioned and will be part of the next release of the Plugin - thanks again fro raising it, I will close the issue now

**Comment by tomh4** [comment]
oh that was fast, thanks alot! keep up the good work, looking forward to try out the new physical hands now as they came out of experimental!
