### ISSUE TITLE
MetaAimHand devices are not removed

### ISSUE THREAD

**Issue by camnewnham** [ultraleap/UnityPlugin#1607]
After following the [instructions](https://docs.ultraleap.com/xr-and-tabletop/xr/unity/xri-integration.html) and using the HandsDemoScene I end up accumulating `MetaAimHand` devices. This is using the "Leap XRHands Subsystem".

Upon clicking play, 4 devices are added (two left and two right hand).

At any one time only two (one left and one right) are providing real input. However, this causes a conflict as the ActionBasedController assigned does not read from the correct one (resulting in an invalid position/rotation). Manually right clicking on all the invalid ones at runtime and removing them resolves the issue.

Upon exiting play mode, only two of the devices are removed, hence the accumulation over time. 

![image](https://github.com/ultraleap/UnityPlugin/assets/19278856/6cd5deee-978c-4730-8f9a-7310f95ad033)

**Comment by camnewnham** [comment]
Thanks! What's the release cadence for patches like these?

**Comment by MattGrayUL** [comment]
We haven't actually got a regular release cadence, but currently the next release is penciled in for the end of June

I may be able to push it sooner, but it's a little harder to wrangle QA's time for a release! - it may be best for you to grab the changes manually if it's urgent :)

**Comment by camnewnham** [comment]
All good - it was causing some issues with Unity 2022 but I've switched over to Unity 6 preview and the changes to the input system seem to mean the additional devices can be ignored for now 👍 

Thanks again.
