### ISSUE TITLE
How do I differentiate between fingers and tool when using this plugin?

### ISSUE THREAD

**Issue by DanielD2019** [ultraleap/UnityPlugin#1659]
How do I differentiate between fingers and tool when using this plugin?Similar to C++    Pointable::isTool()

**Comment by JamesProvan-UL** [comment]
Hi @DanielD2019.

I've answered your question via our support e-mail, but I will copy the response here.

Tool support was removed in Orion V4 of the LeapSDK. If you are using anything other than the original Leap Motion and V2/V3 of the Leap Motion software, tool detection will not work. As such it is not supported in our latest Unity plugin.

Please see here for how to get hand tracking data including the fingers:
[https://docs.ultraleap.com/xr-and-tabletop/xr/unity/plugin/features/scripting-fundamentals.html](https://docs.ultraleap.com/xr-and-tabletop/xr/unity/plugin/features/scripting-fundamentals.html)

Thanks,
Jim
