### ISSUE TITLE
Add Hand Utilities page

### ISSUE THREAD

**Issue by nickjbenson** [ultraleap/UnityPlugin#816]
Originally, we had a hand utilities page planned for our Wiki documtenation, but it got cut for time. It would be good to write a page that documents:

- The basic structure of a Hand object 
- The utilities on Hand objects available in HandUtils.cs
- Ways of getting useful, gesture-related information about a hand via a Hand object

A good organizational structure would be:

- Retrieval: How to get a hold of a Hand object, e.g., Hands.Left and Hands.Right, or directly from a LeapProvider
- Querying: The structure of Hand objects, then how to get useful information out of them
- Manipulation: Hand post-processes and basic transformation.

**Comment by MaxPalmer-UH** [comment]
Covered by work in current documentation push started in V5.3/V5.4 @ElliotPadfieldUL  
Clsoing this.
