### ISSUE TITLE
Persist a warped hand per space/anchor

### ISSUE THREAD

**Issue by nickjbenson** [ultraleap/UnityPlugin#817]
Barrett and Martin's project reveals a significant issue when working with curved interaction objects within close proximity of non-curved (or differently-curved) interaction objects. When the primary hover transitions from a non-curved object to a curved object, the warped representation of the hand sharply changes, and hover information for _all_ interaction objects (curved or otherwise) also sharply changes to reflect the new warping.

The workaround Barrett is attempting is to reconstruct the non-warped interaction objects in an entirely different Interaction Manager with its own hand representations, et cetera. Fundamentally, this solves the problem by allowing interaction objects in a curved space to only ever look at a curved hand, and non-curved interaction objects to only look at a non-curved hand.

The fix that naturally arises from this:
- After the hover broad-phase, figure out all unique curved spaces the hand must exist in (only calculate those spaces that were found in broad-phase).
- Construct and maintain representations of the hand (that is, the InteractionController) for each curved space found in the broad-phase.
- Finish hover processing, but only provide hand information from the same space that an interaction object is in.

**Comment by MaxPalmer-UH** [comment]
Curved object support has been dropped as a native part of the plugin. One possibly for @MattFiler to be aware of with the launcher.
