### ISSUE TITLE
[IE] InteractionSlider OnContactBegin / OnContactEnd rapid oscillation over sustained contact

### ISSUE THREAD

**Issue by nickjbenson** [ultraleap/UnityPlugin#834]
On Martin's machine, IE Example Scene 2 is showing that the horizontal slider produces rapid OnContactBegin / OnContactEnd oscillations. This is strange because I'm pretty sure we added hysteresis to contact distances, but we need to look at this again because having this happen is _super bad_.

@martinschubertleapmotion

**Comment by Amarcolina** [comment]
Does it happen with hands or controller?  Also do you mean it happens when it is pressed, or just when the scene itself starts without any interaction?

**Comment by protodeep** [comment]
I'm seeing similar behavior on an InteractionToggle button.

Tested a fix from @jselstad 

In ContactBone.cs

- remove magnitude checks on lines 151 & 184

- change deltaTime multiplier on line 187 from 10f to 20f

This fix corrects the behavior in the scene I'm currently working in.

**Comment by MaxPalmer-UH** [comment]
The suggested fix never made it to develop / a release. Should be reconsidered for an upcoming release.

**Comment by MaxPalmer-UH** [comment]
Suggested fix still appears to have the desired outcome in reducing the number of OnContactBegin/OnContactEnd events on a slider button. Suggest rolling this into an upcoming release.

Logged as UNITY-493 - closing here.

**Comment by MaxPalmer-UH** [comment]
Fix has been pushed and MR open.
