### ISSUE TITLE
Create wiki page about interpolate / extrapolate / service provider

### ISSUE THREAD

**Issue by Amarcolina** [ultraleap/UnityPlugin#853]
Create a wiki page that discusses the combinations of these parameters:
 - fixed delta time
 - application framerate
 - rigidbody interpolation
 - frame optimization (provider setting)
 - physics extrapolation (provider setting)

Some of the combinations of settings are good and some are bad, and it's not immediately obvious which is which.

**Comment by MaxPalmer-UH** [comment]
Closing here. Tracked as UNITY-747
