### ISSUE TITLE
Add support for hand states from the Detectors module to HandUtils

### ISSUE THREAD

**Issue by nickjbenson** [ultraleap/UnityPlugin#856]
Our deprecated Detectors supported basic detection logic for things like a "thumbs-up" -- that's specifically one that we don't have a simple extension method for in HandUtils.cs, so we should make sure those exist and work correctly so that developers have one-line access to that sort of detection logic.

**Comment by MaxPalmer-UH** [comment]
Closing this as dectection utils have been brought back.

**Comment by MaxPalmer-UH** [comment]
@ElliotPadfieldUL making you aware of this as a potential feature for the Hands module.
