### ISSUE TITLE
High-velocity behavior on InteractionSliders when releasing a grasp outside the slider plane

### ISSUE THREAD

**Issue by nickjbenson** [ultraleap/UnityPlugin#867]
It may have something to do with the spring forces applied to the slider not behaving well with the grasp. @jselstad, would you be able to take a look at this and hypothesize about the cause?

To reproduce:
- Open the Basic UI scene and grasp either slider
- Pull your hand out towards you, away from the slider plane
- Release the grasp, and observe the slider behave erratically for a moment.

Reproduced on both `develop` and `master`.

**Comment by MaxPalmer-UH** [comment]
Closing here. Tracked as UNITY-749.
