### ISSUE TITLE
"isContactingObject" Boolean Variable For InteractionHand Class

### ISSUE THREAD

**Issue by dyanikoglu** [ultraleap/UnityPlugin#882]
Current version of Interaction Module (1.1.0) has **InteractionHand** class with _.isGraspingObject_ and _.isPrimaryHovering_ booleans, but no _.isContactingObject_.

When I need to check out if a hand contacting any objects, I'm getting list of all contacting objects via _.contactingObjects_ and checking it's length, which is inefficient way to do this.

Is it possible to add this missing boolean to **InteractionHand** class in next release?

Thank you.

**Comment by nickjbenson** [comment]
Sure, `.isContactingObject` sounds like a useful API function to be able to call.

However, there's no need to iterate through `contactingObjects` in the mean time! `contactingObjects` is a `ReadonlyHashSet`, not a List, so you can just do `contactingObjects.Contains(intObj)`.

**Comment by MaxPalmer-UH** [comment]
Closing here. Tracking as UNITY-752.
