### ISSUE TITLE
Support interpolation for rigidbodies

### ISSUE THREAD

**Issue by Amarcolina** [ultraleap/UnityPlugin#885]
Currently unity kinda freaks out if a kinematic rigidbody has interpolation turned on.  This prevents us from correctly using the interaction engine in specific situations, and can make the buttons/sliders respond incorrectly or inaccurately.  We are currently waiting on a bugfix from Unity.

In the meantime, interpolation cannot be used for kinematic rigidbodies :(

**Comment by nickjbenson** [comment]
Any update on that bugfix?

**Comment by Amarcolina** [comment]
Got a response on the bug report today, not good news, sounds like it's not planned to be fixed :/

>Our developers have checked the issue, and send more information about this issue. Unfortunately, it's not planned to fix, but you can easily work around it. Here's the answer:
This issue happens because of updating Transform conflicts with physics simulation. Ideally, Rigidbody's motion should be solely owned by the physics engine. Having Transforms and updating Rigidbodies (in this case, via a parent game object) conflicts what physics engine is doing. Although often this does not raise a noticeable issue, it is for sure not an ideal use case. The case could get worse especially when you have interpolation turned on, or lower physics update frequency.

**Comment by MaxPalmer-UH** [comment]
Closing here. Tracked as UNITY-753.
