### ISSUE TITLE
Add tests / more robust support for dynamically enabling and disabling InteractionBehaviours and whole InteractionManagers

### ISSUE THREAD

**Issue by nickjbenson** [ultraleap/UnityPlugin#895]
One of our developers expressed a user story wherein they desired to have the ability to enable and disable the Interaction Engine as a solution for a specific setup, when trying to insert it into an existing project. They already had a solution for Oculus & Vive controllers and sought to use the Interaction Engine for Leap-specific situations only. However, they had to modify InteractionBehaviour to see if their special 'platform' enum was set to "Leap" to be able to enable and disable the whole Interaction Engine.

Enabling and disabling the interaction engine should be as simple as enabling and disabling the Interaction Manager; there shouldn't be any additional work involved. InteractionBehaviours who lack an Interaction Manager or who have their managers disabled should simply become no-op components -- and potentially also disable themselves to provide peace of mind that they really aren't doing anything.

Since the Interaction Engine also modifies things like object Layers and isKinematic state, we'll essentially need to make sure that InteractionBehaviours remember the pre-IE state of any Rigidbodies or Colliders that it may modify while the engine is active. When the engine is re-enabled, we don't have to resume Controller<>Object relationships, but obviously things like layers need to be adjusted again.

We should also have tests for this, to make sure that we don't spew errors or produce unexpected behavior when entire Interaction Managers turn on and off.

**Comment by MaxPalmer-UH** [comment]
Closing here. Tracking as Unity-755.
