### ISSUE TITLE
Freeze Rotation not respected when grasping Kinematic InteractionBehaviours

### ISSUE THREAD

**Issue by nickjbenson** [ultraleap/UnityPlugin#957]
As the title says. Freeze Position works because it switches the grasped movement handler to the pivot-solve mode.

There's a workaround: Using the nonkinematic grasped movement type on the interaction object, because applied velocities respect the rigidbody constraint settings.

Fixing this bug probably means putting a check just after the solved grasped rotation is returned, that will check for the rotation constraint and project the solved rotation down into the closest rotation that satisfies the constraint. (It's not immediately obvious to me how to do this, though.)

**Comment by MaxPalmer-UH** [comment]
Closing here. Tracked as Unity-756
