### ISSUE TITLE
Better behavior in Leap-enabled scenes where there's no device available

### ISSUE THREAD

**Issue by nickjbenson** [ultraleap/UnityPlugin#976]
There are various situations in a practical development cycle where, for example, I want to hop into a scene to modify something but don't have a Leap device plugged in or a service running. Sometimes I don't have a VR headset either.

To get around the VR issue, I can just remove XR support from the project. Unfortunately, Leap components don't behave as gracefully when there isn't actually a source of hands. (I take responsibility for most if not all of these! :P )

- [x] `develop` currently causes an annoying "No Leap Service found" message a couple of times when running any scene because of code I wrote that tries to shoehorn developer command gestures into any scene that is loaded.
  - [ ] (Also, those gestures should load into DontDestroyOnLoad anyway, like our DevGui stuff.)

- [ ] I've implemented a testing InteractionTestController to be able to test the Interaction Engine in a situation that lacks Leap data or VR controllers -- this should be pulled into Core and tested

- [ ] We should also make use of the LeapTestProvider to drive hand data where hand-related testing is desired but there's no Leap device available.

In general, we want to make sure it's not an actively gross experience to try and work with scenes that expect Leap data to exist but don't actually have a device available.

**Comment by MaxPalmer-UH** [comment]
Closing here. Tracked externally as UNITY-761
